# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  update-vcpkg-cache:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v5
          with:
            submodules: 'true'
  
        - name: Install latest CMake and Ninja.
          uses: lukka/get-cmake@latest
  
        - name: Setup vcpkg
          uses: lukka/run-vcpkg@v11.5
          env:
            VCPKG_BINARY_SOURCES: default,rw
  
        - uses: actions/cache/restore@v4.2.4
          with:
            path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
            key: ${{ runner.os }}-vcpkg-cache-${{ hashFiles('**/TestPipeline/vcpkg.json') }} 
  
        - name: Build vcpkg
          uses: lukka/run-vcpkg@v11.5
          with:
            runVcpkgInstall: true
            vcpkgJsonGlob: '**/TestPipeline/vcpkg.json'
          env:
            VCPKG_BINARY_SOURCES: default,rw
        
        - uses: actions/cache/save@v4.2.4
          with:
            path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
            key: ${{ runner.os }}-vcpkg-cache-${{ hashFiles('**/TestPipeline/vcpkg.json') }}

        - run: echo "Current dir:"
        - run: pwd
        
        - run: echo "Top-level contents:"
        - run: "ls"
        
        - run: echo "Check intermediate path:"
        - run: "ls ./969f6665-88a2-4c98-938e-ca9259871fec"
        
        - run: echo "Final vcpkg_cache dir:"
        - run: "ls ./969f6665-88a2-4c98-938e-ca9259871fec/vcpkg_installed/"
        - run: echo "Final vcpkg_cache dir:"
        - run: "ls ./969f6665-88a2-4c98-938e-ca9259871fec/vcpkg_cached/"
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
